CREATE DATABASE TaskTapAz

USE TaskTapAz

CREATE TABLE Brands
(
	Name NVARCHAR(20),
	Id INT PRIMARY KEY IDENTITY
)

CREATE TABLE Models
(
	Name NVARCHAR(20),
	Id INT PRIMARY KEY IDENTITY,
	BrandId INT FOREIGN KEY (BrandId) REFERENCES Brands(Id)
)

CREATE TABLE Colors
(
	Name NVARCHAR(30),
	Id INT PRIMARY KEY IDENTITY
)

CREATE TABLE Phones 
(
	Yeni NVARCHAR(20),
	Memory INT,
	Id INT PRIMARY KEY IDENTITY,
	Delivery NVARCHAR(20),
	ModelId INT FOREIGN KEY (ModelId) REFERENCES Models(Id),
	ColorId INT FOREIGN KEY (ColorId) REFERENCES Colors(Id)
)



